project:
  type: book
  output-dir: docs

book:
  title: "Data Science Portfolio"
  author: "**Basir Talayee**"
  date: "09/06/2024"
  reader-mode: true
   
 

  
  chapters:
    - index.qmd
    - part: activities/README.qmd
      chapters: 
      - activities/activity-01.qmd
      - activities/activity-02.qmd
      - activities/activity-03.qmd
      - activities/quarto-demo.qmd
      - activities/03-univariate-viz-notes.qmd
      
    
    - part: refelections/README.qmd
      chapters: 
      - refelections/refelection.qmd
  
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true
    css: styles.css  # Add this line to include your custom CSS files


execute:
  cache: true
  freeze: auto
